
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ubuntu

development:
  <<: *default
  database: Playlist_development


test:
  <<: *default
  database: Playlist_test

production:
  <<: *default
  database: Playlist_production
  password: 
