# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbf9504ee5b29c77af4b1e27d3363735703132b340d0245b7515eea68ccadedf1333e20f5e81e49d9097368649c798fc6be91e8d0cf475bf2e80ee3bd4fd305c

test:
  secret_key_base: 0d7cc51cf1325c300f3b3f569191b287127a2b510d282d7f70776d881987d22a209689813c8fc4f98bb2a3752929ddc75f481c2df7752d5386a89ec151a6b59e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
